### ISSUE TITLE
regenerate all exercise and example posts with new format

### ISSUE THREAD

**Issue by shiffman** [shiffman/learningprocessing.com#36]
```
pde-files: 
  -
    url: /code/LearningProcessing/chp09_arrays/example_09_10_array_interactive_objects/example_09_10_array_interactive_objects.pde
    github: pathtogithub
  - 
    url: /code/LearningProcessing/chp09_arrays/example_09_10_array_interactive_objects/Stripe.pde
    github: pathtogithub
    label: sketch-2
js-files: 
  -  
    url: /code/LearningProcessing-p5.js/chp09_arrays/example_09_10_array_interactive_objects/sketch.js
    github: pathtogithub
  - 
    url: /code/LearningProcessing-p5.js/chp09_arrays/example_09_10_array_interactive_objects/stripe.js
    github: pathtogithub
```
